# create pod spec to my-test-app:latest  image
apiVersion: v1
kind: Pod
metadata:
  name: my-test-app
spec:
  containers:
  - name: my-test-app
    image: my-test-app:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"